### ISSUE TITLE
AttributeError: 'float' object has no attribute 'backward'

### ISSUE THREAD

**Issue by wangjiaxu** [v-mipeng/LexiconNER#7]
我在跑代码的过程中，遇到了如下的问题，有小伙伴知道这个问题要怎么解决嘛？所用的pytorch版本是1.1.0，python3的环境。
Traceback (most recent call last):
  File "feature_pu_model.py", line 272, in <module>
    acc, risk, prisk, nrisk = trainer.train_mini_batch(batch, args)
  File "feature_pu_model.py", line 136, in train_mini_batch
    (risk).backward()
AttributeError: 'float' object has no attribute 'backward'

**Comment by wangjiaxu** [comment]
这个问题已经解决了，把相应的变量转换为tensor即可，具体是把函数的四个返回值全转换为tensor，若有其他的办法请回复评论，谢谢，
